markdown_extensions:
- sane_lists
- smarty
- toc:
    permalink: true
nav:
- Home:
  - The Bitflow Project: https://bitflow.readthedocs.io/en/latest/
  - Data Sources, Sinks and Format: https://bitflow.readthedocs.io/en/latest/data-format/
  - Core functionality: https://bitflow.readthedocs.io/en/latest/core-functionality/
  - Bitflow Script: bitflow-script.md
  - Naming Conventions: https://bitflow.readthedocs.io/en/latest/naming/
  - Development Process: https://bitflow.readthedocs.io/en/latest/development/
- Implementations:
  - go-bitflow: https://bitflow.readthedocs.io/projects/go-bitflow/en/latest/
  - bitflow4j: https://bitflow.readthedocs.io/projects/bitflow4j/en/latest/
  - python-bitflow: https://bitflow.readthedocs.io/projects/python-bitflow/en/latest/
- Related Projects:
  - bitflow-collector: https://bitflow.readthedocs.io/projects/go-bitflow-collector/en/latest/
  - bitflow-coordinator (Github): https://github.com/bitflow-stream/bitflow-coordinator
  - bitflow-process-agent (Github): https://github.com/bitflow-stream/bitflow-process-agent
plugins:
- search
repo_url: https://github.com/bitflow-stream/antlr-grammars
site_author: Anton Gulenko
site_description: Bitflow Script Documentation
site_name: Go Bitflow
theme: readthedocs
